[build]
  base = "Frontend/"
  command = "npm run build"
  publish = "dist"  # Correct for Vite

[[redirects]]
from = "/sitemap.xml"
to = "https://gameon-c4e7.onrender.com/sitemap.xml"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
